### ISSUE TITLE
fast的版本是实时更新在这里吗？

### ISSUE THREAD

**Issue by TianHanChen** [fast-codesign/fast-xilinx_zynq7000#1]
如何获得fast-0.3.X版本的软件代码？
使用irouter设备，应该部署哪个版本的软件代码？

**Comment by Winters123** [comment]
1. 可直接使用FAST-OpenBox_S4-impl/fast-sw/中的代码。
2. 目前github的上传的软件代码既支持OpenBox S4平台，也支持iRouter。区别在于在S4上需要使用**交叉编译**方式进行编译（S4的使用了基于ARM的CPU），而iRouter是对代码进行直接编译（iRouter使用的是x86架构CPU）。

然而，根据我们开发力量和用户需求的综合考虑，目前iRouter的硬件代码还未针对FAST 2.0进行更新。

p.s. 如果有必要，我们也会针对irouter进行整体代码库的更新。请问同学来自哪所学校？
